Add FOREGROUND_SERVICE permission to manifest.
Apparently required for target SDK version 28 and above:
https://stackoverflow.com/a/52382711/6882947

The app dies at startup otherwise:

AndroidRuntime: java.lang.RuntimeException: Unable to
  create service org.erat.nup.NupService:
  java.lang.SecurityException: Permission Denial:
  startForeground from pid=25462, uid=10174 requires
  android.permission.FOREGROUND_SERVICE