build: Compile with SDK 30 and update Gradle plugin.
Upgrade a bunch of build-related stuff without updating the
targeted or minimum SDK version:

- com.android.tools.build:gradle 2.3.0 -> 4.1.0
- compileSdkVersion 26 -> 30
- buildToolsVersion 26.0.2 -> 30.0.3

Also remove dexOptions.incremental, since it's apparently a
no-op now and produces a warning.

I was hoping that using newer tools would be a simple
change, but I had to fix a bunch of other things:

- Add google and jcenter repos to top-level build.gradle.
- Explicitly use android.test.mock in nup/build.gradle.
- Change compile to implementation and testCompile to
  testImplementation to avoid deprecation warnings.
- android.test.mock.MockContext seems to throw on
  construction now, so update CoverLoader's c'tor to take
  the cache directory instead of a Context to fix
  CoverLoaderTest. Apparently the correct approach now is to
  use Robolectric for mocks.
- Fix a malformed (?) path in browse_menu.xml to fix "AAPT:
  error: '@+drawable/ic_menu_play_clip' is incompatible with
  attribute icon (attr) reference."